-- 1- INSERTAR CUSTOMER
INSERT INTO `smsbd`.`CUSTOMER`
(`ID_CUSTOMER`,`NAME`,`LAST_NAME`,`ADDRESS`,`CITY`,`PROVINCE`,`STATUS`) VALUES 
(NULL,'PRUEBA ','Martini','Paraguay 1141', 'Rosario','Santa Fe','E');
SET @ID_CUSTOMER_VAR := (SELECT ID_CUSTOMER FROM CUSTOMER ORDER BY ID_CUSTOMER DESC LIMIT 1);
-- 2- INSERTAR SIMCARDS DEL CUSTOMER Y STATION
-- 2.1. SIMCARD DEL CUSTOMER
INSERT INTO `smsbd`.`SIMCARD`
(`ID_SIMCARD`,`NUMBER`,`COMPANY`,`ID_CUSTOMER`) VALUES (NULL,'PRUEBA','CLARO', @ID_CUSTOMER_VAR);
SET @ID_SIMCARD_CUS := (SELECT ID_SIMCARD FROM SIMCARD ORDER BY ID_SIMCARD DESC LIMIT 1);
-- 2.2. SIMCARD DE LA ESTACION
INSERT INTO `smsbd`.`SIMCARD`
(`ID_SIMCARD`,`NUMBER`,`COMPANY`,`ID_CUSTOMER`) VALUES (NULL,'PRUEBA1','CLARO', NULL);
SET @ID_SIMCARD_EST := (SELECT ID_SIMCARD FROM SIMCARD ORDER BY ID_SIMCARD DESC LIMIT 1);

-- 3- INSERTAR STATION_INFORMATION
INSERT INTO `smsbd`.`STATION_INFORMATION` (`ID_STATION_INFORMATION`,`ALTITUDE`,`LATITUDE`,`LOCATION_NAME`,`LONGITUDE`) 
VALUES (NULL, 116, -33.056325,'Estacion La Posta',-60.872324);
SET @ID_STATION_INFO_VAR := (SELECT ID_STATION_INFORMATION FROM STATION_INFORMATION ORDER BY ID_STATION_INFORMATION DESC LIMIT 1);

-- 4- INSERTAR STATION
INSERT INTO `smsbd`.`STATION`
(`ID_STATION`,`ENABLE`,`ID_SIMCARD`,`ID_CUSTOMER`,`ID_STATION_INFORMATION`,`IS_DEFAULT`) 
VALUES (NULL,1,@ID_SIMCARD_EST, @ID_CUSTOMER_VAR,@ID_STATION_INFO_VAR, 1);
SET @ID_STATION_VAR := (SELECT ID_STATION FROM STATION ORDER BY ID_STATION DESC LIMIT 1);

-- 5- INSERTAR STATION_PERIODICAL_NOTIFICATION
INSERT INTO `smsbd`.`STATION_PERIODICAL_NOTIFICATION`
(`ID_STATION_PERIODICAL_NOTIFICATION`,`ID_STATION`,`MONDAY`,`TUESDAY`,`WEDNESDAY`,`THURSDAY`,`FRIDAY`,`SATURDAY`,`SUNDAY`,`HOUR`,`SMS_NOTIFICATION_ENABLE`,`EMAIL_NOTIFICATION_ENABLE`)
VALUES (NULL,@ID_STATION_VAR, 0,0,0,0,0,0,0,'19:00:00',0,0);

-- 6- INSERTAR USUARIOS DE LA ESTACION
INSERT INTO `smsbd`.`USER`
(`ID_USER`,`NAME`,`LAST_NAME`,`EMAIL`,`ID_SIMCARD`,`IS_ACTIVE`,`IS_ADMIN`,`PASSWORD`,`ID_CUSTOMER`) 
VALUES (NULL,'Usuario 1','Apellido Us1','usuario1@techner.com.ar', NULL, 1, 1, 'password', @ID_CUSTOMER_VAR);

-- 7- INSERTAR EMAILS DE NOTIFICACION DE USUARIOS
INSERT INTO `smsbd`.`EMAIL` (`ID_EMAIL`,`ID_CUSTOMER`,`EMAIL`) 
VALUES (NULL, @ID_CUSTOMER_VAR, 'email@email.com');

-- 8- INSERTAR STATION_VARIABLE CON VARIABLES HABILITADAS.
INSERT INTO `smsbd`.`STATION_VARIABLE` (`ID_VARIABLE`, `ID_STATION`, `ENABLE`) 
VALUES (1, @ID_STATION_VAR, 1), (2, @ID_STATION_VAR, 1),(3, @ID_STATION_VAR, 1),(7,@ID_STATION_VAR, 1),
(8, @ID_STATION_VAR, 1),(9, @ID_STATION_VAR, 1),(5, @ID_STATION_VAR, 1),(4, @ID_STATION_VAR, 0);